version: '3.8'

services:
  db:
    image: mysql:8

    environment:
      MYSQL_ROOT_PASSWORD: secure_password
      MYSQL_DATABASE: localhost
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
     # - mysql_data:/var/lib/mysql
    #  - ./localhost.sql:/docker-entrypoint-initdb.d/localhost.sql
     # - ./db:/docker-entrypoint-initdb.d
       - $PWD/localhost.sql:/docker-entrypoint-initdb.d/localhost.sql

    #  - ./db/my.cnf:/etc/mysql/my.cnf

volumes:
  mysql_data:
